services:
  mongodb:
    image: mongo:7
    container_name: gym-class-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--username",
          "admin",
          "--password",
          "password",
          "--authenticationDatabase",
          "admin",
          "--eval",
          "db.adminCommand('ping')"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - gym-class-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gym-class-api
    ports:
      - "5127:5127"
    environment:
      Mongo__ConnectionString: "mongodb://admin:password@mongodb:27017/?authSource=admin"
      Mongo__DatabaseName: "gym_class_booking_db"
      Booking__MaxSpotsPerUser: "5"
      Booking__BookingFeePercent: "0.00"
      Booking__AllowBookingAfterStart: "false"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - gym-class-network

volumes:
  mongo_data:

networks:
  gym-class-network:
    driver: bridge
